#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(git -C "$script_dir" rev-parse --show-toplevel 2>/dev/null || true)"
if [[ -z "$repo_root" ]]; then
  repo_root="$(cd "$script_dir/../../../.." && pwd)"
fi
reload_entry="./skills/aki-codex-session-reload/scripts/codex_skills_reload/session_start.sh"
set_active_entry="./skills/aki-codex-session-reload/scripts/codex_skills_reload/set_active_project.sh"

runtime_dir="$repo_root/.codex/runtime"
skills_snapshot="$runtime_dir/codex_skills_reload.md"
project_snapshot="$runtime_dir/codex_project_reload.md"
session_snapshot="$runtime_dir/codex_session_start.md"
handoff_file="$repo_root/mcp/runtime/SESSION_HANDOFF.md"
codex_home="${CODEX_HOME:-$HOME/.codex}"
codex_config_file="$codex_home/config.toml"
github_toolsets_default="${GITHUB_MCP_DEFAULT_TOOLSETS:-context,repos,issues,projects,pull_requests,labels}"

"$script_dir/skills_reload.sh" >/dev/null
"$script_dir/project_reload.sh" >/dev/null
mkdir -p "$runtime_dir"

mapfile -t loaded_skills < <(find "$repo_root/skills" -mindepth 2 -maxdepth 2 -type f -name "SKILL.md" | sort)
declare -a managed_skills=()
declare -a delegated_skills=()
for abs_path in "${loaded_skills[@]}"; do
  rel_path="${abs_path#$repo_root/}"
  skill_name="$(basename "$(dirname "$abs_path")")"
  if [[ "$skill_name" == aki-* ]]; then
    managed_skills+=("$rel_path")
  else
    delegated_skills+=("$rel_path")
  fi
done

active_project=""
active_readme=""
active_task=""
active_agent=""
active_meeting_notes=""
if [[ -f "$project_snapshot" ]]; then
  active_project="$(grep -E '^- Project Root:' "$project_snapshot" | sed -E 's/^- Project Root: `([^`]+)`/\1/' || true)"
  active_readme="$(grep -E '^- Project README:' "$project_snapshot" | sed -E 's/^- Project README: `([^`]+)`/\1/' || true)"
  active_task="$(grep -E '^- Task Doc:' "$project_snapshot" | sed -E 's/^- Task Doc: `([^`]+)`/\1/' || true)"
  active_agent="$(grep -E '^- Project Agent:' "$project_snapshot" | sed -E 's/^- Project Agent: `([^`]+)`/\1/' || true)"
  active_meeting_notes="$(grep -E '^- Meeting Notes:' "$project_snapshot" | sed -E 's/^- Meeting Notes: `([^`]+)`/\1/' || true)"
fi

handoff_status="NONE"
handoff_created=""
handoff_reason=""
if [[ -s "$handoff_file" ]]; then
  handoff_status="PENDING"
  handoff_created="$(grep -E '^- Created At:' "$handoff_file" | head -n 1 | sed -E 's/^- Created At: `([^`]+)`/\1/' || true)"
  handoff_reason="$(grep -E '^- Reason:' "$handoff_file" | head -n 1 | sed -E 's/^- Reason: ?//' || true)"
fi

github_mcp_status="NOT_CONFIGURED"
if [[ -f "$codex_config_file" ]] && grep -Eq '^\[mcp_servers\.github\]' "$codex_config_file"; then
  github_mcp_status="CONFIGURED"
fi

skills_status="OK"
project_status="OK"
runtime_status="OK"

required_runtime_scripts=(
  "$repo_root/skills/aki-codex-core/scripts/create-backup-point.sh"
  "$repo_root/skills/aki-codex-precommit/scripts/validate-precommit-chain.sh"
  "$repo_root/skills/aki-codex-precommit/scripts/run-project-api-script-tests.sh"
  "$repo_root/skills/aki-codex-session-reload/scripts/sync-skill.sh"
  "$repo_root/skills/aki-codex-session-reload/scripts/run-skill-hooks.sh"
  "$repo_root/skills/aki-codex-session-reload/scripts/codex_skills_reload/session_start.sh"
  "$repo_root/skills/aki-codex-session-reload/scripts/codex_skills_reload/skills_reload.sh"
  "$repo_root/skills/aki-codex-session-reload/scripts/codex_skills_reload/project_reload.sh"
  "$repo_root/skills/aki-codex-session-reload/scripts/codex_skills_reload/set_active_project.sh"
  "$repo_root/skills/aki-codex-session-reload/scripts/codex_skills_reload/init_project_docs.sh"
)

missing_runtime_scripts=()
for s in "${required_runtime_scripts[@]}"; do
  if [[ ! -x "$s" ]]; then
    missing_runtime_scripts+=("${s#$repo_root/}")
  fi
done

if [[ ! -f "$skills_snapshot" || "${#loaded_skills[@]}" -eq 0 ]]; then
  skills_status="WARN"
fi

if [[ -z "$active_project" || "$active_project" == "(not selected)" ]]; then
  project_status="WARN"
fi

if [[ "${#missing_runtime_scripts[@]}" -gt 0 ]]; then
  runtime_status="WARN"
fi

now_human="$(date '+%Y-%m-%d %H:%M:%S')"
now_ver="$(date '+%Y%m%d-%H%M%S')"

{
  echo "# Codex Session Start"
  echo
  echo "- Version: \`$now_ver\`"
  echo "- Updated At: \`$now_human\`"
  echo "- Generated By: \`skills/aki-codex-session-reload/scripts/codex_skills_reload/session_start.sh\`"
  echo
  echo "## Startup Checks"
  echo "- Skills Snapshot: \`$skills_status\`"
  echo "- Project Snapshot: \`$project_status\`"
  echo "- Skills Runtime Integrity: \`$runtime_status\`"
  if [[ "$runtime_status" == "WARN" ]]; then
    echo "- Missing/Non-Executable: \`$(IFS=', '; echo "${missing_runtime_scripts[*]}")\`"
    echo "- Action: \`chmod +x skills/aki-codex-core/scripts/*.sh skills/aki-codex-precommit/scripts/*.sh skills/aki-codex-session-reload/scripts/*.sh skills/aki-codex-session-reload/scripts/codex_skills_reload/*.sh\`"
  fi
  echo
  echo "## Loaded Skills"
  if [[ "${#loaded_skills[@]}" -eq 0 ]]; then
    echo "1. \`(none)\`"
  else
    idx=1
    for abs_path in "${loaded_skills[@]}"; do
      rel_path="${abs_path#$repo_root/}"
      skill_name="$(basename "$(dirname "$abs_path")")"
      scope_tag="delegated"
      if [[ "$skill_name" == aki-* ]]; then
        scope_tag="managed"
      fi
      echo "$idx. [${scope_tag}] \`$rel_path\`"
      idx=$((idx + 1))
    done
  fi
  echo
  echo "## Skill Management Scope"
  echo "- Managed Policy: \`skills/aki-*\`를 전역 관리 대상으로 사용"
  echo "- Delegated Policy: 비-\`aki\` 스킬은 Active Project 요구 시에만 사용"
  echo "- Managed Count: \`${#managed_skills[@]}\`"
  echo "- Delegated Count: \`${#delegated_skills[@]}\`"
  if [[ "${#delegated_skills[@]}" -gt 0 ]]; then
    echo "- Delegated Skills:"
    for skill_path in "${delegated_skills[@]}"; do
      echo "  - \`$skill_path\`"
    done
  fi
  echo
  echo "## Active Project"
  if [[ -n "$active_project" && "$active_project" != "(not selected)" ]]; then
    echo "- Project Root: \`$active_project\`"
    [[ -n "$active_readme" ]] && echo "- Project README: \`$active_readme\`"
    [[ -n "$active_task" ]] && echo "- Task Doc: \`$active_task\`"
    [[ -n "$active_agent" ]] && echo "- Project Agent: \`$active_agent\`"
    [[ -n "$active_meeting_notes" ]] && echo "- Meeting Notes: \`$active_meeting_notes\`"
  else
    echo "- Project Root: \`(not selected)\`"
    echo "- Action: \`$set_active_entry <project-root>\`"
  fi
  echo
  echo "## Session Handoff"
  if [[ "$handoff_status" == "PENDING" ]]; then
    echo "- Status: \`PENDING\`"
    echo "- File: \`mcp/runtime/SESSION_HANDOFF.md\`"
    [[ -n "$handoff_created" ]] && echo "- Created At: \`$handoff_created\`"
    [[ -n "$handoff_reason" ]] && echo "- Reason: $handoff_reason"
    echo "- Action: \`mcp/runtime/SESSION_HANDOFF.md\`를 먼저 읽고 이어서 진행"
  else
    echo "- Status: \`NONE\`"
  fi
  echo
  echo "## GitHub MCP Init"
  echo "- Init Mode: \`guide_only\`"
  echo "- Server Config: \`$github_mcp_status\`"
  echo "- Default Toolsets: \`$github_toolsets_default\`"
  if [[ "$github_mcp_status" == "CONFIGURED" ]]; then
    echo "- Execution Status: \`NOT_EXECUTED\`"
    echo "- Action Guide: \`skills/aki-mcp-github/SKILL.md\`의 init flow로 \`$github_toolsets_default\` enable + 재검증"
    echo "- Report Contract: 실행 후 \`enabled\`/\`failed\`/\`unsupported\` 목록을 세션 보고에 포함"
    echo "- Note: 이 스크립트는 MCP toolset enable을 직접 실행하지 않고 가이드만 출력"
  else
    echo "- Execution Status: \`BLOCKED\`"
    echo "- Action Guide: \`~/.codex/config.toml\`에 \`[mcp_servers.github]\` 등록 후 세션 재시작"
  fi
  echo
  echo "## How It Works"
  echo "1. 전역 규칙은 \`AGENTS.md\` + \`skills/*/SKILL.md\`에서 로드"
  echo "2. 프로젝트 컨텍스트는 Active Project의 \`README.md\` + \`prj-docs/PROJECT_AGENT.md\` + \`prj-docs/meeting-notes/README.md\`에서 로드"
  echo "3. 멀티 프로젝트에서는 Active Project를 명시적으로 전환해서 충돌 방지"
  echo
  echo "## Multi Project Guide"
  echo "1. 프로젝트 목록 확인: \`$set_active_entry --list\`"
  echo "2. 활성 프로젝트 지정: \`$set_active_entry <project-root>\`"
  echo "3. 지정 후 \`$reload_entry\` 재실행"
  echo
  echo "## Quick Remind"
  echo "- 시작 문구: \`AGENTS.md만 읽고 시작해.\`"
  echo "- 세션 상태 문서: \`.codex/runtime/codex_session_start.md\`"
  echo "- 재시작 핸드오프: \`mcp/runtime/SESSION_HANDOFF.md\` (있으면 우선 로드)"
  echo "- 문제 시 재동기화: \`$reload_entry\`"
  echo
  echo "## Usage"
  echo "1. 세션 시작 시 \`$reload_entry\` 실행"
  echo "2. \`.codex/runtime/codex_session_start.md\` 기준으로 세션 첫 상태를 보고"
} > "$session_snapshot"

echo "updated: ${session_snapshot#$repo_root/}"
echo "skills: ${#loaded_skills[@]} ($skills_status)"
echo "project: ${active_project:-none} ($project_status)"
