#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(git -C "$script_dir" rev-parse --show-toplevel 2>/dev/null || true)"
if [[ -z "$repo_root" ]]; then
  repo_root="$(cd "$script_dir/../../../.." && pwd)"
fi
runtime_dir="$repo_root/.codex/runtime"
output_file="$runtime_dir/codex_skills_reload.md"

version="$(date +%Y%m%d-%H%M%S)"
updated_at="$(date '+%Y-%m-%d %H:%M:%S')"

collect_skill_files() {
  local skill_root=""
  local -a roots=(
    "$repo_root/skills"
    "$repo_root/.agents/skills"
  )

  for skill_root in "${roots[@]}"; do
    if [[ -d "$skill_root" ]]; then
      find "$skill_root" -mindepth 2 -maxdepth 2 -type f -name "SKILL.md"
    fi
  done | sort -u
}

mapfile -t skill_files < <(collect_skill_files)
mkdir -p "$runtime_dir"

{
  echo "# Codex Skills Reload"
  echo
  echo "- Version: \`$version\`"
  echo "- Updated At: \`$updated_at\`"
  echo "- Generated By: \`skills/aki-codex-session-reload/scripts/codex_skills_reload/skills_reload.sh\`"
  echo
  echo "## Loaded Skills"
  if [[ ${#skill_files[@]} -eq 0 ]]; then
    echo "1. \`(none)\`"
  else
    idx=1
    for abs_path in "${skill_files[@]}"; do
      rel_path="${abs_path#$repo_root/}"
      echo "$idx. \`$rel_path\`"
      idx=$((idx + 1))
    done
  fi
  echo
  echo "## Usage"
  echo "1. 기본 리로드는 \`./skills/aki-codex-session-reload/scripts/codex_skills_reload/session_start.sh\` 사용 (권장)"
  echo "2. 이 파일은 내부 단계로 갱신되며, 필요 시 단독 실행 가능"
} > "$output_file"

echo "updated: $output_file"
echo "skill_count: ${#skill_files[@]}"
