#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage: sync_mcp_config.sh [--mode guide|apply] [--quiet] [--config <path>] [--template <path>]

Modes:
  guide  Check missing MCP sections and print action (default)
  apply  Idempotently append missing MCP sections from template blocks

Environment:
  MCP_CONFIG_SYNC_MODE   guide|apply (default: guide)
USAGE
}

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(git -C "$script_dir" rev-parse --show-toplevel 2>/dev/null || true)"
if [[ -z "$repo_root" ]]; then
  repo_root="$(cd "$script_dir/../../../.." && pwd)"
fi

codex_home="${CODEX_HOME:-$HOME/.codex}"
config_file="$codex_home/config.toml"
template_file="$repo_root/skills/aki-codex-session-reload/references/templates/mcp-config-template.toml"
mode="${MCP_CONFIG_SYNC_MODE:-guide}"
quiet_mode="false"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --mode)
      mode="$2"
      shift 2
      ;;
    --quiet)
      quiet_mode="true"
      shift
      ;;
    --config)
      config_file="$2"
      shift 2
      ;;
    --template)
      template_file="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "[mcp-config-sync] unknown arg: $1" >&2
      usage
      exit 1
      ;;
  esac
done

mode="$(printf '%s' "$mode" | tr '[:upper:]' '[:lower:]')"
if [[ "$mode" != "guide" && "$mode" != "apply" ]]; then
  echo "[mcp-config-sync] invalid --mode: $mode" >&2
  exit 1
fi

if [[ "$config_file" != /* ]]; then
  config_file="$repo_root/$config_file"
fi
if [[ "$template_file" != /* ]]; then
  template_file="$repo_root/$template_file"
fi

config_dir="$(dirname "$config_file")"

declare -A section_patterns=()
section_patterns[github]='^\[mcp_servers\.github\]$'
section_patterns[github_env]='^\[mcp_servers\.github\.env\]$'
section_patterns[playwright]='^\[mcp_servers\.playwright\]$'
section_patterns[openaiDeveloperDocs]='^\[mcp_servers\.openaiDeveloperDocs\]$'
section_patterns[figma]='^\[mcp_servers\.figma\]$'
section_patterns[figma-desktop]='^\[mcp_servers\.(figma-desktop|"figma-desktop")\]$'

required_sections=(
  github
  github_env
  playwright
  openaiDeveloperDocs
  figma
  figma-desktop
)

section_block() {
  local section_name="$1"
  case "$section_name" in
    github)
      cat <<'BLOCK'
[mcp_servers.github]
command = "docker"
args = ["run", "-i", "--rm", "-e", "GITHUB_PERSONAL_ACCESS_TOKEN", "ghcr.io/github/github-mcp-server", "stdio", "--dynamic-toolsets"]
BLOCK
      ;;
    github_env)
      cat <<'BLOCK'
[mcp_servers.github.env]
GITHUB_PERSONAL_ACCESS_TOKEN = "${GITHUB_PERSONAL_ACCESS_TOKEN}"
BLOCK
      ;;
    playwright)
      cat <<'BLOCK'
[mcp_servers.playwright]
command = "npx"
args = ["@playwright/mcp@latest", "--browser", "chrome", "--cdp-endpoint", "http://127.0.0.1:9222"]
BLOCK
      ;;
    openaiDeveloperDocs)
      cat <<'BLOCK'
[mcp_servers.openaiDeveloperDocs]
url = "https://developers.openai.com/mcp"
BLOCK
      ;;
    figma)
      cat <<'BLOCK'
[mcp_servers.figma]
url = "https://mcp.figma.com/mcp"
BLOCK
      ;;
    figma-desktop)
      cat <<'BLOCK'
[mcp_servers.figma-desktop]
url = "http://127.0.0.1:3845/mcp"
BLOCK
      ;;
    *)
      return 1
      ;;
  esac
}

section_exists() {
  local section_name="$1"
  local pattern="${section_patterns[$section_name]}"
  [[ -f "$config_file" ]] && grep -Eq "$pattern" "$config_file"
}

append_section() {
  local section_name="$1"
  local block=""
  block="$(section_block "$section_name")"
  if [[ ! -f "$config_file" ]]; then
    mkdir -p "$config_dir"
    cat > "$config_file" <<'HEADER'
# Auto-generated by sync_mcp_config.sh
# Local overrides are allowed. Keep secrets as environment variable references.

HEADER
  fi

  if [[ -s "$config_file" ]]; then
    printf '\n' >> "$config_file"
  fi
  printf '%s\n' "$block" >> "$config_file"
}

get_toml_section_value() {
  local section_name="$1"
  local key_name="$2"
  if [[ ! -f "$config_file" ]]; then
    return 0
  fi
  awk -v section="[${section_name}]" -v key="${key_name}" '
    $0 == section { in_section=1; next }
    in_section && /^\[/ { exit }
    in_section && $1 == key {
      line=$0
      sub(/^[^=]+=[[:space:]]*/, "", line)
      gsub(/^[[:space:]]+|[[:space:]]+$/, "", line)
      print line
      exit
    }
  ' "$config_file"
}

strip_wrapped_quotes() {
  local value="$1"
  value="${value#\"}"
  value="${value%\"}"
  echo "$value"
}

declare -a added_sections=()
declare -a missing_sections=()

if [[ ! -f "$template_file" ]]; then
  sync_status="ERROR"
  action="fix_template_path:${template_file}"
  github_token_source="unknown"
  github_token_state="UNKNOWN"
else
  for section_name in "${required_sections[@]}"; do
    if section_exists "$section_name"; then
      continue
    fi

    if [[ "$mode" == "apply" ]]; then
      append_section "$section_name"
      added_sections+=("$section_name")
    else
      missing_sections+=("$section_name")
    fi
  done

  # Re-check after apply to report any still missing.
  if [[ "$mode" == "apply" ]]; then
    missing_sections=()
    for section_name in "${required_sections[@]}"; do
      if ! section_exists "$section_name"; then
        missing_sections+=("$section_name")
      fi
    done
  fi

  github_token_value="$(get_toml_section_value "mcp_servers.github.env" "GITHUB_PERSONAL_ACCESS_TOKEN" || true)"
  github_token_value="$(strip_wrapped_quotes "$github_token_value")"
  if [[ -z "$github_token_value" ]]; then
    github_token_source="external_or_unset"
    github_token_state="UNSET_OR_EXTERNAL"
  elif [[ "$github_token_value" =~ ^\$\{?[A-Za-z_][A-Za-z0-9_]*\}?$ ]]; then
    github_token_source="env_ref"
    github_token_state="EXTERNAL_REF"
  elif [[ "$github_token_value" =~ ^(<[^>]+>|REDACTED|redacted|CHANGEME|changeme|\*+)$ ]]; then
    github_token_source="placeholder"
    github_token_state="PLACEHOLDER"
  elif [[ "$github_token_value" =~ ^(ghp_|gho_|ghu_|ghs_|ghr_|github_pat_) ]]; then
    github_token_source="inline_plaintext"
    github_token_state="INLINE_PLAINTEXT"
  else
    github_token_source="custom_inline_value"
    github_token_state="CUSTOM"
  fi

  if [[ "${#missing_sections[@]}" -eq 0 ]]; then
    sync_status="OK"
    action="none"
  else
    sync_status="WARN"
    action="./skills/aki-codex-session-reload/scripts/codex_skills_reload/sync_mcp_config.sh --mode apply"
  fi
fi

added_csv="none"
missing_csv="none"
if [[ "${#added_sections[@]}" -gt 0 ]]; then
  added_csv="$(IFS=','; echo "${added_sections[*]}")"
fi
if [[ "${#missing_sections[@]}" -gt 0 ]]; then
  missing_csv="$(IFS=','; echo "${missing_sections[*]}")"
fi

if [[ "$quiet_mode" != "true" ]]; then
  echo "[mcp-config-sync] mode=$mode status=$sync_status"
  echo "[mcp-config-sync] config=$config_file"
  echo "[mcp-config-sync] template=$template_file"
  echo "[mcp-config-sync] missing=$missing_csv"
  echo "[mcp-config-sync] added=$added_csv"
  echo "[mcp-config-sync] github_token_source=$github_token_source"
  if [[ "$action" != "none" ]]; then
    echo "[mcp-config-sync] action=$action"
  fi
fi

echo "MCP_CONFIG_SYNC_STATUS=$sync_status"
echo "MCP_CONFIG_SYNC_MODE=$mode"
echo "MCP_CONFIG_FILE=$config_file"
echo "MCP_CONFIG_TEMPLATE=$template_file"
echo "MCP_CONFIG_MISSING=$missing_csv"
echo "MCP_CONFIG_ADDED=$added_csv"
echo "MCP_CONFIG_ACTION=$action"
echo "MCP_GITHUB_TOKEN_SOURCE=$github_token_source"
echo "MCP_GITHUB_TOKEN_SOURCE_STATE=$github_token_state"
